# Basic site settings
title: Mach Codebase Tutorial (AI‑gen)
description: "A comprehensive, AI‑generated tutorial to understanding the Mach codebase—walk through diagrams, best practices, and callouts."
keywords: ["Mach engine", "zig", "codebase", "tutorial", "under the hood", "AI-generated"]
url: "https://mnbnkr.github.io"
baseurl: "/mach-codebase-tutorial"

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Jekyll plugins (GitHub Pages includes both)
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# SEO tag configuration
seo:
  title: "{{ page.title }} · Mach Codebase Tutorial"
  description: "{{ page.excerpt | strip_html | truncate: 160 }}"
  url: "{{ page.url | absolute_url }}"
  # twitter:
  #   username: mnbnkr
  # facebook:
  #   publisher: https://facebook.com/yourPage

# Feed
feed:
  path: feed.xml

# Navigation
nav:
  - GitHub: "https://github.com/mnbnkr/mach-codebase-tutorial"

# Aux links (upper right)
aux_links:
  "View on GitHub":
    - "https://github.com/mnbnkr/mach-codebase-tutorial"

# Color scheme
color_scheme: dark

# Author
author:
  name: AI with mnbnkr
  url: https://github.com/mnbnkr

# Permalinks
permalink: /:title/

# Open Graph / Social
# social_image: "/assets/images/og-default.png"
# google_site_verification: "YOUR_VERIFICATION_TOKEN"

# Mermaid
mermaid:
  version: "11.6.0"
  config: |
    directionLR

# custom callouts
callouts:
  warning:
    title: Warning
    color: blue     # theme will use $blue-300 under the hood
  note:
    title: Note
    color: grey-dk  # theme will use $grey-dk-300
  best-practice:
    title: Best Practice
    color: blue

# # Callouts
# callouts:
#   warning:
#     title: Warning
#     color: red
#   note:
#     title: Note
#     color: blue
#   best-practice:
#     title: Best Practice
#     color: green

# Search box
search:
  enabled: true
  placeholder: "Search the tutorial…"

# (You can still remove nav_sort if you prefer explicit nav order)
